<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Backend</RootNamespace>
    <AssemblyName>Backend</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.2"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.3"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="9.0.3"/>
    <PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.11"/>
  </ItemGroup>
</Project>